name: Auto Restart PebbleHost Bot

on:
  push:
    branches:
      - main

jobs:
  restart:
    runs-on: ubuntu-latest

    steps:
      - name: Restart PebbleHost Server
        run: |
          STATUS=$(curl -s -o response.txt -w "%{http_code}" \
          -X POST "https://api.pebblehost.com/api/client/servers/${{ secrets.PTERO_SERVER_ID }}/power" \
          -H "Authorization: Bearer ${{ secrets.PTERO_API_KEY }}" \
          -H "Accept: application/json" \
          -H "Content-Type: application/json" \
          -H "User-Agent: TCW-Bot-Updater/1.0 (Contact: CelxsteAdmin@proton.me)" \
          -d '{"signal":"restart"}')

          echo "HTTP Status: $STATUS"
          cat response.txt
